!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitppcolloc_data(f2pysetupfunc)
      use ppcolloc_data, only : coef
      use ppcolloc_data, only : ncoef
      use ppcolloc_data, only : breaks
      use ppcolloc_data, only : npiece
      use ppcolloc_data, only : l
      use ppcolloc_data, only : kpm
      external f2pysetupfunc
      call f2pysetupfunc(coef,ncoef,breaks,npiece,l,kpm)
      end subroutine f2pyinitppcolloc_data

      
      subroutine f2pyinitcolloc_data(f2pysetupfunc)
      use colloc_data, only : xside
      use colloc_data, only : iside
      use colloc_data, only : rho
      use colloc_data, only : itermx
      use colloc_data, only : k
      use colloc_data, only : m
      external f2pysetupfunc
      call f2pysetupfunc(xside,iside,rho,itermx,k,m)
      end subroutine f2pyinitcolloc_data

      
      subroutine f2pyinitl2approx_data(f2pysetupfunc)
      use l2approx_data, only : ltkmax
      use l2approx_data, only : lpkmax
      use l2approx_data, only : coef
      use l2approx_data, only : k
      use l2approx_data, only : breaks
      use l2approx_data, only : l
      external f2pysetupfunc
      call f2pysetupfunc(ltkmax,lpkmax,coef,k,breaks,l)
      end subroutine f2pyinitl2approx_data

      
      subroutine f2pyinitl2ir_data(f2pysetupfunc)
      use l2ir_data, only : ntau
      use l2ir_data, only : tau
      use l2ir_data, only : weight
      use l2ir_data, only : ntmax
      use l2ir_data, only : totalw
      use l2ir_data, only : gtau
      external f2pysetupfunc
      call f2pysetupfunc(ntau,tau,weight,ntmax,totalw,gtau)
      end subroutine f2pyinitl2ir_data


