C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapddot (ddotf2pywrap, n, dx, incx, dy, incy
     &)
      external ddot
      integer(kind=4) n
      integer(kind=4) incx
      integer(kind=4) incy
      real(kind=8) dx(*)
      real(kind=8) dy(*)
      real(kind=8) ddotf2pywrap, ddot
      ddotf2pywrap = ddot(n, dx, incx, dy, incy)
      end


      subroutine f2pywrapdnrm2 (dnrm2f2pywrap, n, x, incx)
      external dnrm2
      integer(kind=4) n
      integer(kind=4) incx
      real(kind=8) x(*)
      real(kind=8) dnrm2f2pywrap, dnrm2
      dnrm2f2pywrap = dnrm2(n, x, incx)
      end

