iiex_obj = iiex.o
ivex_obj = ivex.o
ixex_obj = ixex.o
xex1_obj = xex1.o bsplvb.o interv.o
xex2_obj = xex2.o bsplvb.o
xex3_obj = xex3.o bsplpp.o bsplvb.o ppvalu.o interv.o
xex4_obj = xex4.o bvalue.o interv.o
xiiex2_obj = xiiex2.o cubspl.o newnot.o
xiiex3_obj = xiiex3.o cubspl.o
xiiex4_obj = xiiex4.o bsplpp.o bsplvb.o
xiiiex1_obj = xiiiex1.o splint.o banfac.o banslv.o bsplpp.o bsplvb.o \
			  ppvalu.o interv.o round.o
xiiiex2_obj = xiiiex2.o splint.o banfac.o banslv.o bsplpp.o bsplvb.o \
			  newnot.o
xiiiex2m_obj = xiiiex2m.o splint.o banfac.o banslv.o bsplpp.o bsplvb.o \
			  newnot.o
xiiiex3_obj = xiiiex3.o titand.o splopt.o splint.o bvalue.o bsplvb.o \
			  banfac.o banslv.o interv.o
xivex1_obj = xivex1.o bsplpp.o bsplvb.o ppvalu.o interv.o smooth.o \
			  setupq.o chol1d.o
reinsch_obj = reinsch.o bsplpp.o bsplvb.o ppvalu.o interv.o smooth.o \
			  setupq.o chol1d.o
xivex2_obj = l2main.o setdatx2.o l2knts.o l2appr.o bsplvb.o \
			  bchfac.o bchslv.o bsplpp.o l2err.o ppvalu.o \
			  interv.o newnot.o
xivex3_obj = l2main.o setdatx3.o l2knts.o l2appr.o bsplvb.o \
			  bchfac.o bchslv.o bsplpp.o l2err.o ppvalu.o \
			  interv.o newnotfk.o
xivex4_obj = l2main.o setdatx4.o titand.o l2knts.o l2appr.o bsplvb.o \
			  bchfac.o bchslv.o bsplpp.o l2err.o ppvalu.o \
			  interv.o newnot.o
xvex_obj = xvex.o colloc.o colpnt.o difequ.o ppvalu.o interv.o knots.o \
			  eqblok.o putit.o bsplvd.o bsplvb.o bsplpp.o newnot.o \
			  slvblktx.o 
xviex2_obj = xviex2.o titand.o tautsp.o ppvalu.o interv.o
xviex3_obj = xviex3.o splint.o bsplvb.o banfac.o banslv.o \
			  bsplpp.o ppvalu.o interv.o
xviiex2_obj = xviiex2.o spli2d.o bsplvb.o banfac.o banslv.o interv.o \
			  bvalue.o 
xviiex3_obj = xviiex3.o spli2d.o bsplvb.o banfac.o banslv.o interv.o \
			  bspp2d.o ppvalu.o

iiex : $(iiex_obj) 
	f77 $(iiex_obj) -o iiex

ivex : $(ivex_obj) 
	f77 $(ivex_obj) -o ivex

ixex : $(ixex_obj) 
	f77 $(ixex_obj) -o ixex

xex1 : $(xex1_obj) 
	f77 $(xex1_obj) -o xex1

xex2 : $(xex2_obj) 
	f77 $(xex2_obj) -o xex2

xex3 : $(xex3_obj)
	f77 $(xex3_obj) -o xex3

xex4 : $(xex4_obj)
	f77 $(xex4_obj) -o xex4

xiiex2 : $(xiiex2_obj)
	f77 $(xiiex2_obj) -o xiiex2

xiiex3 : $(xiiex3_obj)
	f77 $(xiiex3_obj) -o xiiex3

xiiex4 : $(xiiex4_obj)
	f77 $(xiiex4_obj) -o xiiex4

xiiiex1 : $(xiiiex1_obj) 
	f77 $(xiiiex1_obj) -o xiiiex1

xiiiex2 : $(xiiiex2_obj)
	f77 $(xiiiex2_obj) -o xiiiex2

xiiiex2m : $(xiiiex2m_obj)
	f77 $(xiiiex2m_obj) -o xiiiex2m

xiiiex3 : $(xiiiex3_obj) 
	f77 $(xiiiex3_obj) -o xiiiex3

xivex1 : $(xivex1_obj)
	f77 $(xivex1_obj) -o xivex1

reinsch : $(reinsch_obj)
	f77 $(reinsch_obj) -o reinsch

xivex2 : $(xivex2_obj)
	f77 $(xivex2_obj) -o xivex2

xivex3 : $(xivex3_obj)
	f77 $(xivex3_obj) -o xivex3

xivex4 : $(xivex4_obj)
	f77 $(xivex4_obj) -o xivex4

xvex : $(xvex_obj)
	f77 $(xvex_obj) -o xvex

xviex2 : $(xviex2_obj)
	f77 $(xviex2_obj) -o xviex2

xviex3 : $(xviex3_obj)
	f77 $(xviex3_obj) -o xviex3

xviiex2 : $(xviiex2_obj)
	f77 $(xviiex2_obj) -o xviiex2

xviiex3 : $(xviiex3_obj)
	f77 $(xviiex3_obj) -o xviiex3
