C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapbvalue (bvaluef2pywrap, t, bcoef, n, k, x
     &, jderiv)
      external bvalue
      integer(kind=4) n
      integer(kind=4) k
      real(kind=8) x
      integer(kind=4) jderiv
      real(kind=8) t(n+k)
      real(kind=8) bcoef(n)
      real(kind=8) bvaluef2pywrap, bvalue
      bvaluef2pywrap = bvalue(t, bcoef, n, k, x, jderiv)
      end


      subroutine f2pywrapppvalu (ppvaluf2pywrap, breaks, coef, l, 
     &k, x, jderiv)
      external ppvalu
      integer(kind=4) l
      integer(kind=4) k
      real(kind=8) x
      integer(kind=4) jderiv
      real(kind=8) breaks(l + 1)
      real(kind=8) coef(k,l)
      real(kind=8) ppvaluf2pywrap, ppvalu
      ppvaluf2pywrap = ppvalu(breaks, coef, l, k, x, jderiv)
      end


      subroutine f2pywrapround (roundf2pywrap, x, size_bn)
      external round
      real(kind=8) x
      real(kind=8) size_bn
      real(kind=8) roundf2pywrap, round
      roundf2pywrap = round(x, size_bn)
      end

