C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapi4_log_10 (i4_log_10f2pywrap, i)
      external i4_log_10
      integer(kind=4) i
      integer(kind=4) i4_log_10f2pywrap, i4_log_10
      i4_log_10f2pywrap = i4_log_10(i)
      end


      subroutine f2pywrapi4_modp (i4_modpf2pywrap, i, j)
      external i4_modp
      integer(kind=4) i
      integer(kind=4) j
      integer(kind=4) i4_modpf2pywrap, i4_modp
      i4_modpf2pywrap = i4_modp(i, j)
      end


      subroutine f2pywrapi4_uniform_ab (i4_uniform_abf2pywrap, a, 
     &b, seed)
      external i4_uniform_ab
      integer(kind=4) a
      integer(kind=4) b
      integer(kind=4) seed
      integer(kind=4) i4_uniform_abf2pywrap, i4_uniform_ab
      i4_uniform_abf2pywrap = i4_uniform_ab(a, b, seed)
      end


      subroutine f2pywrapi4_wrap (i4_wrapf2pywrap, ival, ilo, ihi)
      external i4_wrap
      integer(kind=4) ival
      integer(kind=4) ilo
      integer(kind=4) ihi
      integer(kind=4) i4_wrapf2pywrap, i4_wrap
      i4_wrapf2pywrap = i4_wrap(ival, ilo, ihi)
      end


      subroutine f2pywrapperm0_check (perm0_checkf2pywrap, n, p)
      external perm0_check
      integer(kind=4) n
      integer(kind=4) p(n)
      integer(kind=4) perm0_checkf2pywrap, perm0_check
      perm0_checkf2pywrap = perm0_check(n, p)
      end


      subroutine f2pywrapperm1_check (perm1_checkf2pywrap, n, p)
      external perm1_check
      integer(kind=4) n
      integer(kind=4) p(n)
      integer(kind=4) perm1_checkf2pywrap, perm1_check
      perm1_checkf2pywrap = perm1_check(n, p)
      end


      subroutine f2pywrapr8_abs (r8_absf2pywrap, x)
      external r8_abs
      real(kind=8) x
      real(kind=8) r8_absf2pywrap, r8_abs
      r8_absf2pywrap = r8_abs(x)
      end


      subroutine f2pywrapr8_acos (r8_acosf2pywrap, c)
      external r8_acos
      real(kind=8) c
      real(kind=8) r8_acosf2pywrap, r8_acos
      r8_acosf2pywrap = r8_acos(c)
      end


      subroutine f2pywrapr8_acosh (r8_acoshf2pywrap, x)
      external r8_acosh
      real(kind=8) x
      real(kind=8) r8_acoshf2pywrap, r8_acosh
      r8_acoshf2pywrap = r8_acosh(x)
      end


      subroutine f2pywrapr8_add (r8_addf2pywrap, x, y)
      external r8_add
      real(kind=8) x
      real(kind=8) y
      real(kind=8) r8_addf2pywrap, r8_add
      r8_addf2pywrap = r8_add(x, y)
      end


      subroutine f2pywrapr8_agm (r8_agmf2pywrap, a, b)
      external r8_agm
      real(kind=8) a
      real(kind=8) b
      real(kind=8) r8_agmf2pywrap, r8_agm
      r8_agmf2pywrap = r8_agm(a, b)
      end


      subroutine f2pywrapr8_aint (r8_aintf2pywrap, x)
      external r8_aint
      real(kind=8) x
      real(kind=8) r8_aintf2pywrap, r8_aint
      r8_aintf2pywrap = r8_aint(x)
      end


      subroutine f2pywrapr8_asin (r8_asinf2pywrap, s)
      external r8_asin
      real(kind=8) s
      real(kind=8) r8_asinf2pywrap, r8_asin
      r8_asinf2pywrap = r8_asin(s)
      end


      subroutine f2pywrapr8_asinh (r8_asinhf2pywrap, x)
      external r8_asinh
      real(kind=8) x
      real(kind=8) r8_asinhf2pywrap, r8_asinh
      r8_asinhf2pywrap = r8_asinh(x)
      end


      subroutine f2pywrapr8_atan (r8_atanf2pywrap, y, x)
      external r8_atan
      real(kind=8) y
      real(kind=8) x
      real(kind=8) r8_atanf2pywrap, r8_atan
      r8_atanf2pywrap = r8_atan(y, x)
      end


      subroutine f2pywrapr8_atanh (r8_atanhf2pywrap, x)
      external r8_atanh
      real(kind=8) x
      real(kind=8) r8_atanhf2pywrap, r8_atanh
      r8_atanhf2pywrap = r8_atanh(x)
      end


      subroutine f2pywrapr8_big (r8_bigf2pywrap)
      external r8_big
      real(kind=8) r8_bigf2pywrap, r8_big
      r8_bigf2pywrap = r8_big()
      end


      subroutine f2pywrapr8_cas (r8_casf2pywrap, x)
      external r8_cas
      real(kind=8) x
      real(kind=8) r8_casf2pywrap, r8_cas
      r8_casf2pywrap = r8_cas(x)
      end


      subroutine f2pywrapr8_ceiling (r8_ceilingf2pywrap, r)
      external r8_ceiling
      real(kind=8) r
      real(kind=8) r8_ceilingf2pywrap, r8_ceiling
      r8_ceilingf2pywrap = r8_ceiling(r)
      end


      subroutine f2pywrapr8_choose (r8_choosef2pywrap, n, k)
      external r8_choose
      integer(kind=4) n
      integer(kind=4) k
      real(kind=8) r8_choosef2pywrap, r8_choose
      r8_choosef2pywrap = r8_choose(n, k)
      end


      subroutine f2pywrapr8_chop (r8_chopf2pywrap, place, x)
      external r8_chop
      integer(kind=4) place
      real(kind=8) x
      real(kind=8) r8_chopf2pywrap, r8_chop
      r8_chopf2pywrap = r8_chop(place, x)
      end


      subroutine f2pywrapr8_cosd (r8_cosdf2pywrap, degrees)
      external r8_cosd
      real(kind=8) degrees
      real(kind=8) r8_cosdf2pywrap, r8_cosd
      r8_cosdf2pywrap = r8_cosd(degrees)
      end


      subroutine f2pywrapr8_cot (r8_cotf2pywrap, angle)
      external r8_cot
      real(kind=8) angle
      real(kind=8) r8_cotf2pywrap, r8_cot
      r8_cotf2pywrap = r8_cot(angle)
      end


      subroutine f2pywrapr8_cotd (r8_cotdf2pywrap, degrees)
      external r8_cotd
      real(kind=8) degrees
      real(kind=8) r8_cotdf2pywrap, r8_cotd
      r8_cotdf2pywrap = r8_cotd(degrees)
      end


      subroutine f2pywrapr8_csc (r8_cscf2pywrap, theta)
      external r8_csc
      real(kind=8) theta
      real(kind=8) r8_cscf2pywrap, r8_csc
      r8_cscf2pywrap = r8_csc(theta)
      end


      subroutine f2pywrapr8_cscd (r8_cscdf2pywrap, degrees)
      external r8_cscd
      real(kind=8) degrees
      real(kind=8) r8_cscdf2pywrap, r8_cscd
      r8_cscdf2pywrap = r8_cscd(degrees)
      end


      subroutine f2pywrapr8_csqrt (r8_csqrtf2pywrap, x)
      external r8_csqrt
      real(kind=8) x
      complex(kind=8) r8_csqrtf2pywrap, r8_csqrt
      r8_csqrtf2pywrap = r8_csqrt(x)
      end


      subroutine f2pywrapr8_cube_root (r8_cube_rootf2pywrap, x)
      external r8_cube_root
      real(kind=8) x
      real(kind=8) r8_cube_rootf2pywrap, r8_cube_root
      r8_cube_rootf2pywrap = r8_cube_root(x)
      end


      subroutine f2pywrapr8_degrees (r8_degreesf2pywrap, radians)
      external r8_degrees
      real(kind=8) radians
      real(kind=8) r8_degreesf2pywrap, r8_degrees
      r8_degreesf2pywrap = r8_degrees(radians)
      end


      subroutine f2pywrapr8_diff (r8_difff2pywrap, x, y, n)
      external r8_diff
      real(kind=8) x
      real(kind=8) y
      integer(kind=4) n
      real(kind=8) r8_difff2pywrap, r8_diff
      r8_difff2pywrap = r8_diff(x, y, n)
      end


      subroutine f2pywrapr8_divide_i4 (r8_divide_i4f2pywrap, i, j)
      external r8_divide_i4
      integer(kind=4) i
      integer(kind=4) j
      real(kind=8) r8_divide_i4f2pywrap, r8_divide_i4
      r8_divide_i4f2pywrap = r8_divide_i4(i, j)
      end


      subroutine f2pywrapr8_e (r8_ef2pywrap)
      external r8_e
      real(kind=8) r8_ef2pywrap, r8_e
      r8_ef2pywrap = r8_e()
      end


      subroutine f2pywrapr8_epsilon (r8_epsilonf2pywrap)
      external r8_epsilon
      real(kind=8) r8_epsilonf2pywrap, r8_epsilon
      r8_epsilonf2pywrap = r8_epsilon()
      end


      subroutine f2pywrapr8_epsilon_compute (r8_epsilon_computef2p
     &ywrap)
      external r8_epsilon_compute
      real(kind=8) r8_epsilon_computef2pywrap, r8_epsilon_compute
      r8_epsilon_computef2pywrap = r8_epsilon_compute()
      end


      subroutine f2pywrapr8_exp (r8_expf2pywrap, x)
      external r8_exp
      real(kind=8) x
      real(kind=8) r8_expf2pywrap, r8_exp
      r8_expf2pywrap = r8_exp(x)
      end


      subroutine f2pywrapr8_factorial (r8_factorialf2pywrap, n)
      external r8_factorial
      integer(kind=4) n
      real(kind=8) r8_factorialf2pywrap, r8_factorial
      r8_factorialf2pywrap = r8_factorial(n)
      end


      subroutine f2pywrapr8_factorial_stirling (r8_factorial_stirl
     &ingf2pywrap, n)
      external r8_factorial_stirling
      integer(kind=4) n
      real(kind=8) r8_factorial_stirlingf2pywrap, r8_factorial_sti
     &rling
      r8_factorial_stirlingf2pywrap = r8_factorial_stirling(n)
      end


      subroutine f2pywrapr8_factorial2 (r8_factorial2f2pywrap, n)
      external r8_factorial2
      integer(kind=4) n
      real(kind=8) r8_factorial2f2pywrap, r8_factorial2
      r8_factorial2f2pywrap = r8_factorial2(n)
      end


      subroutine f2pywrapr8_fall (r8_fallf2pywrap, x, n)
      external r8_fall
      real(kind=8) x
      integer(kind=4) n
      real(kind=8) r8_fallf2pywrap, r8_fall
      r8_fallf2pywrap = r8_fall(x, n)
      end


      subroutine f2pywrapr8_floor (r8_floorf2pywrap, r)
      external r8_floor
      real(kind=8) r
      real(kind=8) r8_floorf2pywrap, r8_floor
      r8_floorf2pywrap = r8_floor(r)
      end


      subroutine f2pywrapr8_fraction (r8_fractionf2pywrap, i, j)
      external r8_fraction
      integer(kind=4) i
      integer(kind=4) j
      real(kind=8) r8_fractionf2pywrap, r8_fraction
      r8_fractionf2pywrap = r8_fraction(i, j)
      end


      subroutine f2pywrapr8_fractional (r8_fractionalf2pywrap, x)
      external r8_fractional
      real(kind=8) x
      real(kind=8) r8_fractionalf2pywrap, r8_fractional
      r8_fractionalf2pywrap = r8_fractional(x)
      end


      subroutine f2pywrapr8_gamma (r8_gammaf2pywrap, x)
      external r8_gamma
      real(kind=8) x
      real(kind=8) r8_gammaf2pywrap, r8_gamma
      r8_gammaf2pywrap = r8_gamma(x)
      end


      subroutine f2pywrapr8_gamma_log (r8_gamma_logf2pywrap, x)
      external r8_gamma_log
      real(kind=8) x
      real(kind=8) r8_gamma_logf2pywrap, r8_gamma_log
      r8_gamma_logf2pywrap = r8_gamma_log(x)
      end


      subroutine f2pywrapr8_huge (r8_hugef2pywrap)
      external r8_huge
      real(kind=8) r8_hugef2pywrap, r8_huge
      r8_hugef2pywrap = r8_huge()
      end


      subroutine f2pywrapr8_hypot (r8_hypotf2pywrap, x, y)
      external r8_hypot
      real(kind=8) x
      real(kind=8) y
      real(kind=8) r8_hypotf2pywrap, r8_hypot
      r8_hypotf2pywrap = r8_hypot(x, y)
      end


      subroutine f2pywrapr8_in_01 (r8_in_01f2pywrap, a)
      external r8_in_01
      real(kind=8) a
      logical(kind=4) r8_in_01f2pywrap, r8_in_01
      r8_in_01f2pywrap = .not.(.not.r8_in_01(a))
      end


      subroutine f2pywrapr8_insignificant (r8_insignificantf2pywra
     &p, r, s)
      external r8_insignificant
      real(kind=8) r
      real(kind=8) s
      logical(kind=4) r8_insignificantf2pywrap, r8_insignificant
      r8_insignificantf2pywrap = .not.(.not.r8_insignificant(r, s)
     &)
      end


      subroutine f2pywrapr8_is_inf (r8_is_inff2pywrap, r)
      external r8_is_inf
      real(kind=8) r
      logical(kind=4) r8_is_inff2pywrap, r8_is_inf
      r8_is_inff2pywrap = .not.(.not.r8_is_inf(r))
      end


      subroutine f2pywrapr8_is_int (r8_is_intf2pywrap, r)
      external r8_is_int
      real(kind=8) r
      logical(kind=4) r8_is_intf2pywrap, r8_is_int
      r8_is_intf2pywrap = .not.(.not.r8_is_int(r))
      end


      subroutine f2pywrapr8_is_nan (r8_is_nanf2pywrap, r)
      external r8_is_nan
      real(kind=8) r
      logical(kind=4) r8_is_nanf2pywrap, r8_is_nan
      r8_is_nanf2pywrap = .not.(.not.r8_is_nan(r))
      end


      subroutine f2pywrapr8_log_2 (r8_log_2f2pywrap, x)
      external r8_log_2
      real(kind=8) x
      real(kind=8) r8_log_2f2pywrap, r8_log_2
      r8_log_2f2pywrap = r8_log_2(x)
      end


      subroutine f2pywrapr8_log_10 (r8_log_10f2pywrap, x)
      external r8_log_10
      real(kind=8) x
      real(kind=8) r8_log_10f2pywrap, r8_log_10
      r8_log_10f2pywrap = r8_log_10(x)
      end


      subroutine f2pywrapr8_log_b (r8_log_bf2pywrap, x, b)
      external r8_log_b
      real(kind=8) x
      real(kind=8) b
      real(kind=8) r8_log_bf2pywrap, r8_log_b
      r8_log_bf2pywrap = r8_log_b(x, b)
      end


      subroutine f2pywrapr8_max (r8_maxf2pywrap, x, y)
      external r8_max
      real(kind=8) x
      real(kind=8) y
      real(kind=8) r8_maxf2pywrap, r8_max
      r8_maxf2pywrap = r8_max(x, y)
      end


      subroutine f2pywrapr8_min (r8_minf2pywrap, x, y)
      external r8_min
      real(kind=8) x
      real(kind=8) y
      real(kind=8) r8_minf2pywrap, r8_min
      r8_minf2pywrap = r8_min(x, y)
      end


      subroutine f2pywrapr8_mod (r8_modf2pywrap, x, y)
      external r8_mod
      real(kind=8) x
      real(kind=8) y
      real(kind=8) r8_modf2pywrap, r8_mod
      r8_modf2pywrap = r8_mod(x, y)
      end


      subroutine f2pywrapr8_modp (r8_modpf2pywrap, x, y)
      external r8_modp
      real(kind=8) x
      real(kind=8) y
      real(kind=8) r8_modpf2pywrap, r8_modp
      r8_modpf2pywrap = r8_modp(x, y)
      end


      subroutine f2pywrapr8_mop (r8_mopf2pywrap, i)
      external r8_mop
      integer(kind=4) i
      real(kind=8) r8_mopf2pywrap, r8_mop
      r8_mopf2pywrap = r8_mop(i)
      end


      subroutine f2pywrapr8_nan (r8_nanf2pywrap)
      external r8_nan
      real(kind=8) r8_nanf2pywrap, r8_nan
      r8_nanf2pywrap = r8_nan()
      end


      subroutine f2pywrapr8_nint (r8_nintf2pywrap, x)
      external r8_nint
      real(kind=8) x
      integer(kind=4) r8_nintf2pywrap, r8_nint
      r8_nintf2pywrap = r8_nint(x)
      end


      subroutine f2pywrapr8_normal_01 (r8_normal_01f2pywrap, seed)
      external r8_normal_01
      integer(kind=4) seed
      real(kind=8) r8_normal_01f2pywrap, r8_normal_01
      r8_normal_01f2pywrap = r8_normal_01(seed)
      end


      subroutine f2pywrapr8_normal_ab (r8_normal_abf2pywrap, a, b,
     & seed)
      external r8_normal_ab
      real(kind=8) a
      real(kind=8) b
      integer(kind=4) seed
      real(kind=8) r8_normal_abf2pywrap, r8_normal_ab
      r8_normal_abf2pywrap = r8_normal_ab(a, b, seed)
      end


      subroutine f2pywrapr8_nth_root (r8_nth_rootf2pywrap, x, n)
      external r8_nth_root
      real(kind=8) x
      integer(kind=4) n
      real(kind=8) r8_nth_rootf2pywrap, r8_nth_root
      r8_nth_rootf2pywrap = r8_nth_root(x, n)
      end


      subroutine f2pywrapr8_pi (r8_pif2pywrap)
      external r8_pi
      real(kind=8) r8_pif2pywrap, r8_pi
      r8_pif2pywrap = r8_pi()
      end


      subroutine f2pywrapr8_pi_sqrt (r8_pi_sqrtf2pywrap)
      external r8_pi_sqrt
      real(kind=8) r8_pi_sqrtf2pywrap, r8_pi_sqrt
      r8_pi_sqrtf2pywrap = r8_pi_sqrt()
      end


      subroutine f2pywrapr8_power (r8_powerf2pywrap, r, p)
      external r8_power
      real(kind=8) r
      integer(kind=4) p
      real(kind=8) r8_powerf2pywrap, r8_power
      r8_powerf2pywrap = r8_power(r, p)
      end


      subroutine f2pywrapr8_pythag (r8_pythagf2pywrap, a, b)
      external r8_pythag
      real(kind=8) a
      real(kind=8) b
      real(kind=8) r8_pythagf2pywrap, r8_pythag
      r8_pythagf2pywrap = r8_pythag(a, b)
      end


      subroutine f2pywrapr8_radians (r8_radiansf2pywrap, degrees)
      external r8_radians
      real(kind=8) degrees
      real(kind=8) r8_radiansf2pywrap, r8_radians
      r8_radiansf2pywrap = r8_radians(degrees)
      end


      subroutine f2pywrapr8_rise (r8_risef2pywrap, x, n)
      external r8_rise
      real(kind=8) x
      integer(kind=4) n
      real(kind=8) r8_risef2pywrap, r8_rise
      r8_risef2pywrap = r8_rise(x, n)
      end


      subroutine f2pywrapr8_round (r8_roundf2pywrap, x)
      external r8_round
      real(kind=8) x
      real(kind=8) r8_roundf2pywrap, r8_round
      r8_roundf2pywrap = r8_round(x)
      end


      subroutine f2pywrapr8_round_i4 (r8_round_i4f2pywrap, x)
      external r8_round_i4
      real(kind=8) x
      integer(kind=4) r8_round_i4f2pywrap, r8_round_i4
      r8_round_i4f2pywrap = r8_round_i4(x)
      end


      subroutine f2pywrapr8_secd (r8_secdf2pywrap, degrees)
      external r8_secd
      real(kind=8) degrees
      real(kind=8) r8_secdf2pywrap, r8_secd
      r8_secdf2pywrap = r8_secd(degrees)
      end


      subroutine f2pywrapr8_sech (r8_sechf2pywrap, x)
      external r8_sech
      real(kind=8) x
      real(kind=8) r8_sechf2pywrap, r8_sech
      r8_sechf2pywrap = r8_sech(x)
      end


      subroutine f2pywrapr8_sign (r8_signf2pywrap, x)
      external r8_sign
      real(kind=8) x
      real(kind=8) r8_signf2pywrap, r8_sign
      r8_signf2pywrap = r8_sign(x)
      end


      subroutine f2pywrapr8_sign3 (r8_sign3f2pywrap, x)
      external r8_sign3
      real(kind=8) x
      real(kind=8) r8_sign3f2pywrap, r8_sign3
      r8_sign3f2pywrap = r8_sign3(x)
      end


      subroutine f2pywrapr8_sign_char (r8_sign_charf2pywrap, x)
      external r8_sign_char
      real(kind=8) x
      character r8_sign_charf2pywrap, r8_sign_char
      r8_sign_charf2pywrap = r8_sign_char(x)
      end


      subroutine f2pywrapr8_sign_match (r8_sign_matchf2pywrap, r1,
     & r2)
      external r8_sign_match
      real(kind=8) r1
      real(kind=8) r2
      logical(kind=4) r8_sign_matchf2pywrap, r8_sign_match
      r8_sign_matchf2pywrap = .not.(.not.r8_sign_match(r1, r2))
      end


      subroutine f2pywrapr8_sign_match_strict (r8_sign_match_stric
     &tf2pywrap, r1, r2)
      external r8_sign_match_strict
      real(kind=8) r1
      real(kind=8) r2
      logical(kind=4) r8_sign_match_strictf2pywrap, r8_sign_match_
     &strict
      r8_sign_match_strictf2pywrap = .not.(.not.r8_sign_match_stri
     &ct(r1, r2))
      end


      subroutine f2pywrapr8_sign_opposite (r8_sign_oppositef2pywra
     &p, r1, r2)
      external r8_sign_opposite
      real(kind=8) r1
      real(kind=8) r2
      logical(kind=4) r8_sign_oppositef2pywrap, r8_sign_opposite
      r8_sign_oppositef2pywrap = .not.(.not.r8_sign_opposite(r1, r
     &2))
      end


      subroutine f2pywrapr8_sign_opposite_strict (r8_sign_opposite
     &_strictf2pywrap, r1, r2)
      external r8_sign_opposite_strict
      real(kind=8) r1
      real(kind=8) r2
      logical(kind=4) r8_sign_opposite_strictf2pywrap, r8_sign_opp
     &osite_strict
      r8_sign_opposite_strictf2pywrap = .not.(.not.r8_sign_opposit
     &e_strict(r1, r2))
      end


      subroutine f2pywrapr8_sind (r8_sindf2pywrap, degrees)
      external r8_sind
      real(kind=8) degrees
      real(kind=8) r8_sindf2pywrap, r8_sind
      r8_sindf2pywrap = r8_sind(degrees)
      end


      subroutine f2pywrapr8_sqrt_i4 (r8_sqrt_i4f2pywrap, i)
      external r8_sqrt_i4
      integer(kind=4) i
      real(kind=8) r8_sqrt_i4f2pywrap, r8_sqrt_i4
      r8_sqrt_i4f2pywrap = r8_sqrt_i4(i)
      end


      subroutine f2pywrapr8_tand (r8_tandf2pywrap, degrees)
      external r8_tand
      real(kind=8) degrees
      real(kind=8) r8_tandf2pywrap, r8_tand
      r8_tandf2pywrap = r8_tand(degrees)
      end


      subroutine f2pywrapr8_tiny (r8_tinyf2pywrap)
      external r8_tiny
      real(kind=8) r8_tinyf2pywrap, r8_tiny
      r8_tinyf2pywrap = r8_tiny()
      end


      subroutine f2pywrapr8_uniform_01 (r8_uniform_01f2pywrap, see
     &d)
      external r8_uniform_01
      integer(kind=4) seed
      real(kind=8) r8_uniform_01f2pywrap, r8_uniform_01
      r8_uniform_01f2pywrap = r8_uniform_01(seed)
      end


      subroutine f2pywrapr8_uniform_ab (r8_uniform_abf2pywrap, a, 
     &b, seed)
      external r8_uniform_ab
      real(kind=8) a
      real(kind=8) b
      integer(kind=4) seed
      real(kind=8) r8_uniform_abf2pywrap, r8_uniform_ab
      r8_uniform_abf2pywrap = r8_uniform_ab(a, b, seed)
      end


      subroutine f2pywrapr8_walsh_1d (r8_walsh_1df2pywrap, x, digi
     &t)
      external r8_walsh_1d
      real(kind=8) x
      integer(kind=4) digit
      real(kind=8) r8_walsh_1df2pywrap, r8_walsh_1d
      r8_walsh_1df2pywrap = r8_walsh_1d(x, digit)
      end


      subroutine f2pywrapr8_wrap (r8_wrapf2pywrap, r, rlo, rhi)
      external r8_wrap
      real(kind=8) r
      real(kind=8) rlo
      real(kind=8) rhi
      real(kind=8) r8_wrapf2pywrap, r8_wrap
      r8_wrapf2pywrap = r8_wrap(r, rlo, rhi)
      end


      subroutine f2pywrapr8_zeta (r8_zetaf2pywrap, p)
      external r8_zeta
      real(kind=8) p
      real(kind=8) r8_zetaf2pywrap, r8_zeta
      r8_zetaf2pywrap = r8_zeta(p)
      end


      subroutine f2pywrapr82_dist_l2 (r82_dist_l2f2pywrap, a1, a2)
      external r82_dist_l2
      real(kind=8) a1(2)
      real(kind=8) a2(2)
      real(kind=8) r82_dist_l2f2pywrap, r82_dist_l2
      r82_dist_l2f2pywrap = r82_dist_l2(a1, a2)
      end


      subroutine f2pywrapr82_eq (r82_eqf2pywrap, a1, a2)
      external r82_eq
      real(kind=8) a1(2)
      real(kind=8) a2(2)
      logical(kind=4) r82_eqf2pywrap, r82_eq
      r82_eqf2pywrap = .not.(.not.r82_eq(a1, a2))
      end


      subroutine f2pywrapr82_ge (r82_gef2pywrap, a1, a2)
      external r82_ge
      real(kind=8) a1(2)
      real(kind=8) a2(2)
      logical(kind=4) r82_gef2pywrap, r82_ge
      r82_gef2pywrap = .not.(.not.r82_ge(a1, a2))
      end


      subroutine f2pywrapr82_gt (r82_gtf2pywrap, a1, a2)
      external r82_gt
      real(kind=8) a1(2)
      real(kind=8) a2(2)
      logical(kind=4) r82_gtf2pywrap, r82_gt
      r82_gtf2pywrap = .not.(.not.r82_gt(a1, a2))
      end


      subroutine f2pywrapr82_le (r82_lef2pywrap, a1, a2)
      external r82_le
      real(kind=8) a1(2)
      real(kind=8) a2(2)
      logical(kind=4) r82_lef2pywrap, r82_le
      r82_lef2pywrap = .not.(.not.r82_le(a1, a2))
      end


      subroutine f2pywrapr82_lt (r82_ltf2pywrap, a1, a2)
      external r82_lt
      real(kind=8) a1(2)
      real(kind=8) a2(2)
      logical(kind=4) r82_ltf2pywrap, r82_lt
      r82_ltf2pywrap = .not.(.not.r82_lt(a1, a2))
      end


      subroutine f2pywrapr82_ne (r82_nef2pywrap, a1, a2)
      external r82_ne
      real(kind=8) a1(2)
      real(kind=8) a2(2)
      logical(kind=4) r82_nef2pywrap, r82_ne
      r82_nef2pywrap = .not.(.not.r82_ne(a1, a2))
      end


      subroutine f2pywrapr82_norm (r82_normf2pywrap, a)
      external r82_norm
      real(kind=8) a(2)
      real(kind=8) r82_normf2pywrap, r82_norm
      r82_normf2pywrap = r82_norm(a)
      end

