C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapr8vec_distinct (r8vec_distinctf2pywrap, n
     &, x)
      external r8vec_distinct
      integer(kind=4) n
      real(kind=8) x(n)
      logical r8vec_distinctf2pywrap, r8vec_distinct
      r8vec_distinctf2pywrap = .not.(.not.r8vec_distinct(n, x))
      end

